// import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar'
export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function ProjectsPage() {
  return (
    <html lang="en">
      <body>
        <Navbar />  {/* <-- Your glassy responsive navbar */}
      </body>
      <section id="about" className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-12">
        <h1 className="text-3xl font-bold mb-4">My Connections</h1>
        <p className="text-[--color-text]">
          This is all my connections.
        </p>
        <div className="grid grid-flow-col grid-rows-3 gap-12 place-content-around ">
          <div className='my-3 w-100'>            
            <a className="bg-neutral-primary-soft block max-w-sm p-6 border border-default rounded-base shadow-xs hover:bg-neutral-secondary-medium">
              <img className="border-2 border-solid rounded-md w-10 my-1" src="https://chuen666666.github.io/img/avatar.jpg" alt="" />
              <h5 className="mb-3 text-2xl font-semibold tracking-tight text-heading leading-8">淳</h5>
              <p className="text-body">群除我佬，我是肺霧</p>
              <a className="flex my-1"href='https://chuen666666.github.io/'>Website</a>
            </a>
          </div>
          {/* <div>01</div>
          <div>01</div>
          <div>01</div>
          <div>01</div>
          <div>01</div>
          <div>01</div>
          <div>09</div> */}
        </div>
        <div className="py-8 grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-12">
        </div>  
      </section>
    </html>
  )
}
