// import './globals.css'
import type { Metadata } from 'next'
import Navbar from '../components/navbar'

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
}

export default function AboutPage() {  
  return (
    <html lang="en">
      <body>
        <Navbar />  {/* <-- Your glassy responsive navbar */}
      </body>
      <section id="about" className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8 py-12">
        {/* <h1 className="text-3xl font-bold mb-4">About Me!</h1> */}
        {/* <p className="text-[--color-text]">
          This is your content area. Scroll to see the sticky, glassy navbar stay put.
        </p> */}

        {/* <div className="py-8 grid lg:grid-cols-3 md:grid-cols-2 sm:grid-cols-1 gap-12"></div> */}
        <div className="grid grid-flow-col grid-rows-2 gap-4">
          <div className="row-span-1 sm:row-span-2 ">
            <img className="h-100 w-90 object-cover mask-r-from-30% rounded-lg" src="./img/wow.jpg" alt="Sunset in the mountains"></img>
          </div>
          <div className=" ">
            <h1 className="text-5xl text-[--color-text]">Muhammad Guarddin</h1>
            <p className="w-full py-8 text-[--color-text] text-wrap text-justify text-left">Hi, my name is Muhammad Guarddin, you can call me Muha, I'm currently a 12th grade student at highschool, and I'm from Indonesia. I like to learn something new that is related to computer and also engineering stuffs, as I hope I could be applied to university major related to that. </p>
           
            <p className="w-full text-[--color-text] text-wrap text-justify"></p>
          
          </div>
        
          </div>
        {/* </div> */}
      </section>
    </html>
  )
}
